### ISSUE TITLE
Can't find cement module

### ISSUE THREAD

**Issue by ghost** [eloquentstore/appimager#17]
Despite installing the needed Python packages, using Appimager still fails with:

```
Traceback (most recent call last):
  File "./appimager", line 2, in <module>
    from core import app
  File "/home/tomascw/Projects/appimager/core/app.py", line 1, in <module>
    from cement.core.foundation import CementApp
ImportError: No module named 'cement'
```

**Comment by chrisnharvey** [comment]
How did you install the Python packages? Are you running Python 3?

This seems to workj for me:

```
pip install -r /path/to/appimager/requirements.txt
```

**Comment by chrisnharvey** [comment]
@tomascw I have just tagged the first [alpha release](https://github.com/eloquentstore/appimager/releases) of AppImager. Could you run it from your CLI and let me know what output you get?

```
./AppImager
```
